### PR TITLE
initial commit with a few data files and working Python API/command line tool

### PR DESCRIPTION
**Pull request by natechols**
@dalexander, @mdsmith, @mpkocher please review.  this works more or less as michael outlined but it's a little clumsy how i'm cramming the data into a python module.  maybe this is good enough for now?

### CODE REVIEW

**Comment by mpkocher** [comment]
Not sure it's the best idea to store the data within the repo?

Can we rsync/scp from /mnt/secondary/Share/{X} until we have a better location to pull the from (e.g., s3) ?

**Comment by natechols** [comment]
I'm open to other suggestions, but we need something that can work with relative paths.  The obvious alternative would be to embed the path to the actual data in the python module (possibly as a separate JSON file).  There may be other ways to do this with python distutils but I'm not very familiar with it.

**Comment by natechols** [comment]
Oh, I misread your comment.  We don't have to put the files here, but they're pretty useless for testing on CircleCI if they only exist on our filesystem.  These are all files that are already in GitHub so far, which we would like to remove from other repositories.

**Comment by mpkocher** [comment]
What about not putting it into a python package and having a flat structure of a single json file (pbdata.json) and a single python script (pbdata) as a starting point?

It could be run 

`pbdata get lambda #assumes pbdata.json in cwd` 

or 

`pbdata get bam01 --bundle=/path/to/my-bundle.json`

`export PB_DATA_BUNDLE=/path/to/bundle.json # data root would be relative to the JSON file`

`pbdata get bam01 --bundle=/path/to/my-bundle.json`

**Comment by pb-cdunn** [comment]
Here was my idea on how to get data from aws:
- https://github.com/PacificBiosciences/pb-cache-fetch
- https://github.com/PacificBiosciences/pb-cache

I think you need to solve separate problems separately. How to obtain a binary file from a URL, and how to store it there as a unique URL in the first place, is completely separate from the _meaning_ of the data in the file.

After we have a reliable datastore (**and a local filesystem caching layer above it**), people can easily write adapters to it. For example, I will use **git-sym** for git repos. But other people will have other ideas. Lots of things become simple.

**Pull request closed without merging**
